name: car_manager
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: 3.2.1
  cloud_firestore: 3.1.18
  collection: 1.16.0
  firebase_core: 1.18.0
  firebase_storage: 10.2.18
  flutter_svg: 1.1.1+1
  geocoding: 2.0.4
  google_fonts: 3.0.1
  google_maps_flutter: 2.1.8
  http: 0.13.4
  image_picker: 0.8.5+3
  intl: 0.17.0
  photo_view: 0.14.0
  provider: 6.0.3
  reorderables: 0.5.0
  shared_preferences: 2.0.15
  syncfusion_flutter_core: 20.2.38
  syncfusion_flutter_sliders: 20.2.38
  url_launcher: 6.1.4
  uuid: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

dependency_overrides:
  firebase_core_platform_interface: 4.4.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
