name: car_manager
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 2.0.15
  collection: 1.15.0
  firebase_core: 1.17.1
  firebase_storage: 10.2.17
  intl: 0.17.0
  photo_view: 0.14.0
  url_launcher: 6.1.3
  reorderables: 0.4.4
  uuid: 3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
